/* tslint:disable */
/* eslint-disable */
/**
 * Odysseus identity manager server
 * A service that handles all authentication processes with 2fa, uses ory hydra to handle OpenID and OAuth2 requests
 *
 * The version of the OpenAPI document: 0.7.1-alpha.5
 * Contact: simoneromano@tutanota.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * New user input data
 * @export
 * @interface LoginInput
 */
export interface LoginInput {
    /**
     * The new user username, must be unique.
     * @type {string}
     * @memberof LoginInput
     */
    email: string;
    /**
     * The new user password.
     * @type {string}
     * @memberof LoginInput
     */
    password: string;
}

export function LoginInputFromJSON(json: any): LoginInput {
    return LoginInputFromJSONTyped(json, false);
}

export function LoginInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginInputToJSON(value?: LoginInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


