/* tslint:disable */
/* eslint-disable */
/**
 * Odysseus identity manager server
 * A service that handles all authentication processes with 2fa, uses ory hydra to handle OpenID and OAuth2 requests
 *
 * The version of the OpenAPI document: 0.7.1-alpha.5
 * Contact: simoneromano@tutanota.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthConsentBody
 */
export interface OAuthConsentBody {
    /**
     * The user authorized these scopes
     * @type {Array<string>}
     * @memberof OAuthConsentBody
     */
    scopes: Array<string>;
}

export function OAuthConsentBodyFromJSON(json: any): OAuthConsentBody {
    return OAuthConsentBodyFromJSONTyped(json, false);
}

export function OAuthConsentBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthConsentBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scopes': json['scopes'],
    };
}

export function OAuthConsentBodyToJSON(value?: OAuthConsentBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scopes': value.scopes,
    };
}


