/* tslint:disable */
/* eslint-disable */
/**
 * Odysseus identity manager server
 * A service that handles all authentication processes with 2fa, uses ory hydra to handle OpenID and OAuth2 requests
 *
 * The version of the OpenAPI document: 0.7.2
 * Contact: simoneromano@tutanota.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Code validation input
 * @export
 * @interface ValidateCode
 */
export interface ValidateCode {
    /**
     * The TOTP code.
     * @type {string}
     * @memberof ValidateCode
     */
    code: string;
}

export function ValidateCodeFromJSON(json: any): ValidateCode {
    return ValidateCodeFromJSONTyped(json, false);
}

export function ValidateCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ValidateCodeToJSON(value?: ValidateCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}


